Defect #30723 xbump over gitlab doesn't fail if asked revision is not present
    1. Improving xutils.xerror.XUtilsError class:

        a) __str__ must be more informative; especially the traceback uses str().

        This (after modifications):

Traceback (most recent call last):
  File "tests/test_gitcmd.py", line 127, in testResolve_abracadabra
    self.cmd.get_hash(URI_LOCAL, 'abracadabra'),
  File "/root/genbox_xutils/tests/../xutils/scm/gitcmd.py", line 111, in get_hash
    num=cmd_ret, error_log=err)
XUtilsError: Git command error (num=128): fatal: Needed a single revision

        is better than (before modifications):

Traceback (most recent call last):
  File "tests/test_gitcmd.py", line 127, in testResolve_abracadabra
    self.cmd.get_hash(URI_LOCAL, 'abracadabra'),
  File "/root/genbox_xutils/tests/../xutils/scm/gitcmd.py", line 110, in get_hash
    raise XUtilsError(error='Git command error', error_log=err)
XUtilsError: Git command error

        b) adding __repr__() implementation

    2. Rewriting the corresponding unittests - tests/test_xerror.py:

        a) adding more tests (with and wihtout num, error_log, repr)

        b) deprecated names have been replaced (failUnlessEqual -> assertEqual)
        https://docs.python.org/3.3/library/unittest.html#deprecated-aliases