fixed all the AttributeError: 'module' object has no attribute 'settings' errors in the test and the xbuilder error when bumping from xbuilder: when BASE_URIs are not defined, get them from portage configs.